# download chicago crime data

all: data/Crimes_-_2001_to_present.csv data/CHIData_forProj.csv

data/Crimes_-_2001_to_present.csv: src/getCrimeData.py
	python src/getCrimeData.py

data/Crimes_-_2001_to_present.csv: src/getCrimeData.py
	python src/getCrimeData.py
