# download data

all: data/CHIData.csv data/CHIData_forProj.csv

data/yelpData.csv: src/get_CHIData.py
	python src/get_CHIData.py

data/yelpData_forProj.csv: src/get_CHIData.py
	python src/get_CHIData.py
