

download:
	xxxxx



db_TBD:	/Users/eyalshiv/DI/musixplore/data/msd_summary_file.h5:
	createTracksDB.py /Users/eyalshiv/DI/musixplore/data/msd_summary_file.h5 MX_DB.txt DB_statistics.txt


# postgresql+brew+MountainLion installation bug fix:
# http://dba.stackexchange.com/questions/21587/postgresql-is-running-locally-but-i-cannot-connect-why

# initdb ~/DI/musixplore/data/work/pgDB/
# postgres -D /Users/eyalshiv/DI/musixplore/data/work/pgDB/ -p 8787
# pg_ctl -D ~/DI/musixplore/data/work/pgDB start
# /usr/local/bin/psql  -p 8787 -d my_db_test

#find . -name "*.pyc" -exec rm -rf {} \;

